version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    postgres:
        image: 'postgres:11.1-alpine'
        working_dir: /project
        volumes:
            - './db:/project'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=db
        ports:
            - '9005:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /project
        volumes:
            - './app:/project'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /project
        volumes:
            - './app:/project'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
